Document: fnsynchro
Title: Debian fnsynchro Manual
Author: <insert document author here>
Abstract: This manual describes what fnsynchro is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fnsynchro/fnsynchro.sgml.gz

Format: postscript
Files: /usr/share/doc/fnsynchro/fnsynchro.ps.gz

Format: text
Files: /usr/share/doc/fnsynchro/fnsynchro.text.gz

Format: HTML
Index: /usr/share/doc/fnsynchro/html/index.html
Files: /usr/share/doc/fnsynchro/html/*.html

  
