#! /bin/bash
file=$1
[ -e $file ] && . $file

command='/usr/bin/fnsynchro'
args="--config=$config --object=$object"

if [ "$notify" != "" ]; then
    mail=$(ldapsearch -h nedi -x -b o=Nokia uid=$notify mail|awk '/mail:/ {print $2}')
    args="$args --notify $mail"
fi

echo $command $args>>/root/adhoc
rm -rf $file
